### ISSUE TITLE
Issues with Docker

### ISSUE THREAD

**Issue by cjlovering** [facebookresearch/torchbeast#3]
After installing docker (on MacOS), the build failed. I am on the latest commit in master.

I get the following message:

```
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "/src/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/src/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/src/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/root/miniconda3/envs/torchbeast/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.
```

**Comment by heiner** [comment]
Hey Charles, thanks for reporting this!

I just pushed https://github.com/facebookresearch/torchbeast/commit/e233fbc3019abe693eb3e30ea560c2445377eb88 which should resolve this issue. Please let us know if you run into further problems.

BTW please note that we had limited success building the Docker image on MacOS as it seems to stall while compiling PyTorch. This may be a resource constraint.

**Comment by edran** [comment]
Hey @cjlovering, did you end up making progress on this?

**Comment by cjlovering** [comment]
> Hey @cjlovering, did you end up making progress on this?

Hello edran, so far no. I tried again with new installs and updated source on MacOS and it did not work. I have not had a chance do so on a linux machine (as I don't have immediate access to one with sufficient permissions). I will be coming back to this issue again soon.

**Comment by bottler** [comment]
Docker Desktop on mac has its own set of resource constraints (controlled in Preferences -> Advanced). I wonder if the internal compiler error is caused by failing to allocate memory due to the constraint.

**Comment by cjlovering** [comment]
Hello! I've stopped trying to get this to work on Mac, and now trying on Google cloud.

I have gotten docker and polybeast to run, but I have not been able do use GPUs with it. Do you have a recommended approach for using docker with GPUs?

**Comment by edran** [comment]
@cjlovering you most likely want to use `nvidia-docker`, and modify our image to:
1. either install cuda;
2. or simply replace https://github.com/facebookresearch/torchbeast/blob/master/Dockerfile#L2 with an image from NVIDIA's hub: https://hub.docker.com/r/nvidia/cuda/ (the 18.04 cudnn one should work in theory).

**Comment by cjlovering** [comment]
@edran Thank you! I did that and it seems that the GPUs are available and cuda is installed. For instance, I was able to run `nvidia-smi` and see the GPU status (by adding another CMD to the dockerfile). However, when the polybeast script is run it does not find that cuda available.

**Comment by edran** [comment]
I don't know whether the base image is enough to pull both cuda and cudnn, and it's possible that both might be required for pytorch to be compiled with cuda support. Try using `10.1-cudnn7-runtime-ubuntu18.04`.

Also, if you share your dockerfile I can give it a go locally to see whether I spot issues.

**Comment by cjlovering** [comment]
Thanks! I will try that soon (Google Cloud is being slow).

Here's the file (with the updated image):
https://github.com/cjlovering/torchbeast/blob/master/Dockerfile
